
//PARKINGSLOT KANISHKA

export const GET_ERRORS = "GET_ERRORS";
export const GET_SLOTS="GET_SLOTS";
export const DELETE_SLOTS="DELETE_SLOTS";
export const GET_SLOT ="GET_SLOT";


//USER ESHA
//export const GET_ERRORS = "GET_ERRORS";
export const GET_USER = "GET_USER";


//ADMIN RUTUJA
export const GET_PARKING_PREMISES = "GET_PARKING_PREMISES";
export const GET_PARKING_PREMISE = "GET_PARKING_PREMISE";
export const DELETE_PREMISE = "DELETE_PREMISE";


//VEHICLE SARAVANA
export const GET_WEIGHTLOGS="GET_WEIGHTlOGS";
export const GET_WEIGHTLOG="GET_WEIGHTLOG";
export const DELETE_WEIGHTLOG ="DELETE_WEIGHTLOG";


//FLOORS YASHWANT2
export const GET_VEHICLES="GET_VEHICLES";
export const GET_VEHICLE="GET_VEHICLE";
export const DELETE_VEHICLE ="DELETE_VEHICLE";